---
- hosts: test
  user: makar
#  gather_facts: no
  become: true
  tasks:
    - name: Set Postfix option hostname
      debconf: name=postifx question="postfix/mailname" value="{{ansible_fqdn}}" vtype="string"

    - name: Set Postfix option type as internet site
      debconf: name=postfix question="postfix/main_mailer_type" value="'Internet Site'" vtype="string"
    
    - name: Install Postfix
      apt: package={{ item }} state=latest force=yes update_cache=yes cache_valid_time=3600
      with_items:
        - postfix
        - mailutils
      tags: "init-postfix"          

    - name: Uninstall Postfix
      apt: package={{ item }} state=absent force=yes update_cache=yes cache_valid_time=3600
      with_items:
        - postfix
        - mailutils
      tags: "drop-postfix"

